<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HomeSampling.API</RootNamespace>
    <UserSecretsId>homesampling-api-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.Infrastructure\Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\Module.Auth\Module.Auth.csproj" />
    <ProjectReference Include="..\Module.Patient\Module.Patient.csproj" />
    <ProjectReference Include="..\Module.Admin\Module.Admin.csproj" />
    <ProjectReference Include="..\Module.Rider\Module.Rider.csproj" />
    <ProjectReference Include="..\Module.Contact\Module.Contact.csproj" />
  </ItemGroup>

</Project>
